version: '3.8'

services:
  InSoLiToDatabase2:
    image: neo4j:4.4.3
    hostname: neodb
    environment:
      - NEO4J_AUTH=none
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_connector_https_advertised__address=:443
    volumes:
      - type: bind
        source: ./DB/InSoLiToImport
        target: /var/lib/neo4j/import
      - ./DB/LOGS:/logs
      - ./DB/DATA:/data
      - ./DB/PLUGINS/neo4j-graph-data-science-1.8.3.jar:/var/lib/neo4j/plugins/graph-data-science.jar
      - ./DB/PLUGINS/apoc-4.4.0.3-all.jar:/var/lib/neo4j/plugins/apoc.jar
      - ./DB/CONF:/var/lib/neo4j/conf
    ports:
      - 7687:7687
      - 7474:7474
    restart: unless-stopped
  
  ApacheServer2:
    image: httpd:2.4.52
    depends_on:
      - node-app
      - InSoLiToDatabase2
    volumes: 
      - type: bind
        source: apache-setup/insolito-httpd.conf
        target: /usr/local/apache2/conf/httpd.conf
        read_only: true
      - type: bind
        source: apache-setup/neo4j-reverse-proxy.conf
        target: /usr/local/apache2/conf/extra/neo4j-reverse-proxy.conf
        read_only: true
      - type: bind
        source: apache-setup/insolito-reverse-proxy.conf
        target: /usr/local/apache2/conf/extra/insolito-reverse-proxy.conf
        read_only: true
    ports:
      - 8080:80
    restart: unless-stopped

  node-app:
    build:
      context: .
      dockerfile: Dockerfile  # Ensure the path to the Dockerfile is correct
    # image: node:20
    volumes:
      # - ./REST/static:/usr/src/app/REST/static    # Mounting bundled files here
      # - ./InSoLiToAPI:/usr/src/app/InSoLiToAPI
      - /usr/src/app/node_modules    # Use a named volume for node_modules to avoid conflicts
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped

    # image: node:20
    # working_dir: /usr/src/app/InSoLiToAPI
    # volumes:
    #   - ./REST/static:/usr/src/app/REST/static    # Mounting bundled files here
    #   - ./InSoLiToAPI:/usr/src/app/InSoLiToAPI
    # command: bash -c "npm install express webpack webpack-cli webpack-dev-middleware html-webpack-plugin && npm run build && node server.js"
    # ports:
    #   - "3000:3000"
    # environment:
    #   NODE_ENV: production

volumes:
  InSoLiToWB:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: ${MTU:-1500}
