version: '1'

services:
  InSoLiToDatabase:
    image: neo4j:4.4.3
    environment:
      - NEO4J_AUTH=none
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_memory_heap_max__size=6G
    volumes:
      - $PWD/DB/InSoLiToImport:/var/lib/neo4j/import
    ports:
      - 7687:7687
      - 7474:7474
  
  ApacheServer:
    image: httpd:2.4.52
    volumes:
      - type: bind
        source: $PWD/REST/static
        target: /usr/local/apache2/htdocs/
    ports:
      - 80:80
volumes:
  InSoLiToWB:
